import pandas as pd
import requests
from bs4 import BeautifulSoup
import re
import json
from src.core.base_scraper import BaseScraper


class PinkberryScraper(BaseScraper):
    """Scraper for Pinkberry locations"""
    
    def scrape(self) -> pd.DataFrame:
        """
        Scrape Pinkberry locations from inline JSON in JavaScript on their map page
        
        Returns:
            pd.DataFrame: Raw location data with standardized columns
        """
        print(f"Scraping Pinkberry locations from inline JavaScript JSON...")
        
        try:
            # URL and parameters from notebook
            url = "https://locator.kahalamgmt.com/locator/index.php"
            params = {
                "brand": "24",
                "mode": "map", 
                "latitude": "34.00125000",
                "longitude": "-118.43066000",
                "q": "90066",
                "pagesize": "1000"  # Get all stores in one request
            }
            
            response = self.session.get(
                url,
                params=params,
                timeout=self.config.get('timeout', 30)
            )
            response.raise_for_status()
            
            # Parse HTML content
            soup = BeautifulSoup(response.text, "html.parser")
            
            # Find all script tags with type="text/javascript" (from notebook pattern)
            script_tags = soup.findAll("script", type="text/javascript")
            
            if len(script_tags) < 2:
                raise ValueError("Not enough script tags found on page")
            
            # Process scripts from index 1 to 72 (from notebook: [1:72])
            stores_list = script_tags[1:72] if len(script_tags) >= 72 else script_tags[1:]
            
            data_list = []
            
            for script_tag in stores_list:
                try:
                    if not script_tag.string:
                        continue
                        
                    # Clean script content (from notebook pattern)
                    script_content = script_tag.string.replace(
                        "// generated by including pagesize parameter", ""
                    )
                    
                    # Extract JSON using regex (from notebook pattern)
                    match = re.search(r"Locator\.stores\['\d+'\] = ({.*?});", script_content)
                    if match:
                        json_content = match.group(1)
                        
                        try:
                            # Parse JSON content into dictionary
                            store_data = json.loads(json_content)
                            data_list.append(store_data)
                        except json.JSONDecodeError as e:
                            print(f"JSON decode error: {e}")
                            continue
                    
                except Exception as e:
                    # Continue processing other scripts if one fails
                    continue
            
            if not data_list:
                raise ValueError("No store data found in JavaScript scripts")
            
            # Convert to DataFrame
            df = pd.DataFrame(data_list)
            
            # Standardize column names to lowercase (API returns capitalized)
            column_mapping = {
                'Name': 'name',
                'Address': 'address', 
                'City': 'city',
                'State': 'state',
                'Zip': 'zip_code',
                'Phone': 'phone',
                'Latitude': 'latitude',
                'Longitude': 'longitude',
                'StoreId': 'store_id'
            }
            
            # Rename columns that exist
            for old_col, new_col in column_mapping.items():
                if old_col in df.columns:
                    df[new_col] = df[old_col]
            
            # Clean up data types
            if 'latitude' in df.columns:
                df['latitude'] = pd.to_numeric(df['latitude'], errors='coerce')
            if 'longitude' in df.columns:
                df['longitude'] = pd.to_numeric(df['longitude'], errors='coerce')
            
            # Clean phone numbers if present
            if 'phone' in df.columns:
                df['phone'] = df['phone'].astype(str).str.strip()
                df['phone'] = df['phone'].replace('', None)
            
            # Select standard columns for our framework
            standard_columns = ['store_id', 'name', 'address', 'city', 'state', 'zip_code', 'phone', 'latitude', 'longitude']
            existing_columns = [col for col in standard_columns if col in df.columns]
            df = df[existing_columns].copy()
            
            print(f"Found {len(df)} Pinkberry locations")
            
            return df
            
        except Exception as e:
            print(f"Error scraping Pinkberry locations: {str(e)}")
            if 'response' in locals():
                print(f"Response status: {response.status_code}")
                print(f"Response URL: {response.url}")
            raise 